name = "siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true

[[kv_namespaces]]
binding = "SIREN"
id = "330b41adda084a8890021c9335ac7c2f"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "ede0fe87-6ba9-4504-a666-3d3830f3c1fe"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/elyoudee/Siren/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/elyoudee/Siren/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/elyoudee/Siren/refs/heads/master/web/link.html"
